server {
    listen 80;
    server_name fila.baja.local;

    root /var/www/baja-app/fila;
    index index.php index.html;

    location /css/ {
        alias /var/www/baja-app/default/css/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /js/ {
        alias /var/www/baja-app/default/js/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /img/ {
        alias /var/www/baja-app/default/img/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location ~ "^/([0-2][0-9](BR|SE|SU|NE))$" {
        return 301 /$1/;
    }

    location ~ "^/([0-2][0-9](BR|SE|SU|NE))/(.*)$" {
        set $event_code $1;
        rewrite ^/([0-2][0-9](BR|SE|SU|NE))/(.*)$ /$3 last;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_pass baja-app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/fila$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PHP_VALUE "auto_prepend_file=/var/www/html/src/bootstrap.php";
        fastcgi_param REDIRECT_EVENT $event_code;
    }
}
