server {
    listen 443 ssl;
    server_name certificado.bajasaebrasil.net;

    ssl_certificate     /etc/letsencrypt/live/bajasaebrasil.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bajasaebrasil.net/privkey.pem;

    root /var/www/baja-app/certificado;
    index index.php index.html;

    location /css/ {
        alias /var/www/baja-app/default/css/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /js/ {
        alias /var/www/baja-app/default/js/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location ~ "^/c/([a-zA-Z0-9]+)/([a-zA-Z0-9]+)$" {
        rewrite ^/c/([a-zA-Z0-9]+)/([a-zA-Z0-9]+)$ /certificado.php?evt=$1&cpf=$2 last;
    }
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_pass baja-app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/certificado$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PHP_VALUE "auto_prepend_file=/var/www/html/src/bootstrap.php";
        fastcgi_param QUERY_STRING $args;
    }
}